### ISSUE TITLE
split code into functional scripts

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#1]
Good start @mpinsky. It'd be nice to start by splitting this code into functional units that we can work on. [This initial script](https://github.com/mpinsky/OceanAdapt/commit/02a3bf095923616d245236ffd2d788bca5e72dcc) has just way too much in one place. We can clean it up!

**Comment by mpinsky** [comment]
Note that we will need to combine it back together before reposting to the
OceanAdapt website

**Comment by rBatt** [comment]
Why?

**Comment by mpinsky** [comment]
We need a version to give the OceanAdapt website so that it can run
(happens automatically after every data update).

But wait.. perhaps an alternative is to link the website to the Git
repository. We would need to link the website to particular versions of the
code, since we will (presumably) have experimental versions that we're
actively revising as well as the production version that the website uses.

We would also need to work it out carefully so that the OceanAdapt website
1) can run off of Git (I'm a little skeptical) and 2) never breaks (perhaps
easier to ensure, but we need to be careful).

**Comment by rBatt** [comment]
OK, these things sound achievable.

I'm assuming that the goal is to have a script that can be sourced, and
then the website updated. We could have a master script that sources other
.R files, each of which currently contain a portion of the current code. We
just need to be consistent with naming directories. Alternatively, we could
write this as an R package, but I'd like to avoid that extra effort for the
time being.

For versioning, what we would do would be to create "branches" than run in
parallel to the 'master' branch.

These are things that are definitely easier to discuss after we're all on
the same page with the current workflow.

**Comment by rBatt** [comment]
@mpinsky I'm giving up on this

**Comment by mpinsky** [comment]
Agreed. Discretion here is the better part of valor,

On Monday, June 22, 2015, Ryan Batt <notifications@github.com> wrote:

> Closed #1 <https://github.com/mpinsky/OceanAdapt/issues/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpinsky/OceanAdapt/issues/1#event-337223073>.
>


-- 
Please excuse, sent from a device with tiny keys...
