### ISSUE TITLE
How to change NEUS to get Fall Season?

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#23]
@mpinsky I need help with this. I'm not sure how I'm supposed to run this code, but I think I know how to change it (although debugging will probably be needed). When I was working with the species names a while back, I never got the code to run for me (even before my attempted changes). Thus, I probably can't test it properly.

### Changes to make to add NEUS Fall to `complete_r_script.R`
- [x] Modify [line that subsets to SPRING](https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L141)
  - [x] delete `neus = neus[SEASON=='SPRING',]`
- [x] Define a new region [e.g., on this line](https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L490)
- [x] Make sure all downstream derived values are calculated by region
  - [x] e.g., see [`presyr = aggregate(list(pres = dat$wtcpue>0), by=list(region = dat$region, spp=dat$spp, common=dat$common, year=dat$year), FUN=sum, na.rm=TRUE) # find which species are present in which years`](https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L554)
  - [x] in the above case, nothing would need to change, b/c after we add a new region, it'll do the calc separately for SPRING and FALL in the NEUS
  - [x] However, [in this example](https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L458), `aggregate` is `by` only `haulid`, `stratum`, `stratumarea` (which is odd, by the way, but is probably done just as a convenient carry over of column values – I've done this kind of thing before, too), `year`, `lat`, `lon`, `depth`, and `spp`. Thus, we'd have to add in `by=list(...., region =neus$region)`
- [x] I do not understand the use of [`regstouse = c('Eastern Bering Sea', 'Northeast US')`](https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L647), so I don't know how it should be changed (or not)
- [x] Similar, [the print out here](https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L791-L792) may or may not need to be changed – I think probably "no" because it's just referring to all seasons in NEUS (i.e., that data set, not the analysis of the separate seasons)
  - [x] Also [here](https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L907-L909)

**Comment by mpinsky** [comment]
I talked to Lucas Marxen a while ago, and the main thing we were doing wrong when running the script was using the wrong datafile. We need to use the raw datafile from OceanAdapt, found here: http://oceanadapt.rutgers.edu/download/

It should then run fine.

Your proposed changes look about right. However, I would run the NEUS spring and NEUS fall datasets separately through the pipeline, rather than keeping them combined. E.g., split them apart on [this line](https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L141) by subsetting into neusspring and neusfall. Then treat them separately from then on (change all subsequent code from neus to neusspring, then duplicate those commands and include them for neusfall). 

Similarly, the printout [here](https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L791-L792) would be duplicated: once for neusspring and once for neusfall.

We can leave the national indicator as just EBS and NEUS spring (selected [here](https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L647))

**Comment by mpinsky** [comment]
Ryan, did you ever get this script to run on your computer? Like I said, it should run fine if you download the data from the website. Then the file names will match.

**Comment by mpinsky** [comment]
Let me change my tune: it does run fine if you download the data from the website. I just uploaded the data to GitHub as a zip (38MB, vs. 380MB unzipped). Unzip and source the script from within the directory, runs well.

**Comment by rBatt** [comment]
@mpinsky see our discussion under the commit that addressed this. There were some typos that I fixed, and things in other commits that I just referenced that are related to this goal. I think it works. You obviously can't just run it in the current state of the repo b/c of the large files. I've put all .csv's on the ignore list, so even if you unpack them locally they won't be recognized by git.
