### ISSUE TITLE
Find data source download URL for metadata

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#26]
For some of the metadata files I was able to get the place where the data could (at least in theory) be downloaded; e.g., here for AI: https://github.com/mpinsky/OceanAdapt/blob/master/R/metadata/metaData.ai.R#L189

As was the case with #25 , I couldn't find this for WCTRI or WCANN, and I actually did download the data for NEUS via iobis.org, but I can't link to how to get to that part of the databse, and it took me about an hour. @mpinsky Also, we actually just got these data from Sean Lucey, so I don't know if those data I was able to download are even comparable (I know they don't contain the corrections etc, but I don't know if there's another reason you went to Lucey).

#17

**Comment by mpinsky** [comment]
That's right: some datasets can be downloaded directly from the web (those from AFSC), others require interaction with a data provider (a person). WCTRI is no longer updated, since the survey has been ended. WCANN comes through a data request to Beth Horness. See [this document](https://github.com/mpinsky/OceanAdapt/blob/master/metaData/docs/Updating%20the%20Indicators%203.docx) for the draft instructions on how to get new data each year.

The NEUS data on iobis.org is out of date (ends in 2008). That's why we get it from Sean Lucey.
