### ISSUE TITLE
Website plots NaNs as 0

### ISSUE THREAD

**Issue by mpinsky** [mpinsky/OceanAdapt#3]
See, for example, NEUS Atlantic hagfish. The website plots the missing data as a 0 latitude and depth, which is clearly wrong. This is something that Lucas and Dan will need to fix.

**Comment by danfarns** [comment]
http://oceanadapt.rutgers.edu/regional_data/  Atlantic hagfish ( Myxine glutinosa )

PHP Script will now convert 'NA'  or 'NaN' to Javascript NaN for the fields "Latitude" and "Depth".
PHP Script will now convert 'NA'  or 'NaN' to 0 for the fields "Latitude_std_err" and "Depth_std_err".

The reason for changing NA/NaN to zero for the "*_std_err" was because setting those values to NaN would cause the graph to have error bars act weird.

Dygraphs should now skip drawing lines to values declared NaN.

**Comment by mpinsky** [comment]
Looks great, thank you.
