### ISSUE TITLE
update.data.R should read all files out of data_raw

### ISSUE THREAD

**Issue by mpinsky** [mpinsky/OceanAdapt#38]
@rBatt Shouldn't the updata.data.R script read all the files it needs from the zip files in data_raw? That is the procedure I described in the How_to_update instructions, and I thought that we were going that way.

I will update the code unless you see a reason not to.

**Comment by rBatt** [comment]
Again, I'm chasing a moving target here. Also, you don't specify what files you think aren't being read-in from the correct location. There are many things going on in that script, so I can't presume to know which instances you have in mind. So I'll try to be explicit.

The most recent flurry of coding and revisions was prompted by  
  1. needed to change the update.data.R code to conform to the extensively rehauled layout of the repo  
  2. ensure that the "updated" data files were actually *completely new* data files from our source (i.e., the source that provides to us)  

Both of these objectives have been met. All issues I have closed have been closed appropriately, and if you disagree, please reopen.  

I used the read me files as a tool to get the job done. The style and exact manner in which I get the job done is a different issue, although I appreciate the notion that *how* things are done can be quite important.

That being said, there are some files that are **not** available in the data_raw folder, that are nonetheless absolutely essential to the workflow that you and lucas have designed, and to which I have tirelessly attempted to adhere. We discussed this issue earlier over GitHub (although I cannot find it right now; maybe over email).

Additionally, there is the issue of where the other **raw data files** are read-in from --- the directory is my downloads folder. I agree that these files should be gathered from the zip files in data_raw. But this is where the moving target comes in -- I've been working feverishly to keep up with the changing expectations, and *just* caught up now. Please understand that this isn't a snub at the read me (although this is the first Issue). First you right code that works, and then, you try to make it efficient and beautiful. If it's getting the right data and everything is works, that's a dramatic improvement in the state of affairs from 48 hours ago.

You can make the changes, but realizes that more errors may occur downstream. To properly test the script, you may find that you need to remove all the relative paths, etc. 

Right now everything works. Depending on what files you are referring to in the issue, it may or may not be necessary to make changes.

**Comment by rBatt** [comment]
OK, see https://github.com/mpinsky/OceanAdapt/releases for my take

**Comment by mpinsky** [comment]
Yes, we are at a good point now. As I said, I will work on improving the
paths, hence why I opened an issue and assigned myself.

On Thursday, August 27, 2015, Ryan Batt <notifications@github.com> wrote:

> OK, see https://github.com/mpinsky/OceanAdapt/releases for my take
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpinsky/OceanAdapt/issues/38#issuecomment-135551378>.
>


-- 
Please excuse, sent from a device with tiny keys...

**Comment by rBatt** [comment]
Yep, gotcha. Just wasn't clear on what you were referring to, and wanted to
make sure we were on the same page, and to be clear that the script is
highly sensitive to the directory (a small change in the repo directory
organization will lead to needing many changes in the script, e.g.).

**Comment by rBatt** [comment]
Okay, after having tried to do this almost a year later, I now see it both ways.

When I started doing this year's update, my first instinct was to download the files, rename them, and put them into the .zip folder in `data_raw`, ha.

I think I was trying to achieve quite a bit when I wrote this code. The idea was that someone would click "download" on AFSC website, then run the script. Done.

The way I read in raw data in the trawlData packages makes more sense to me. Well, for one thing it's functionalized, rather than a script. So you make the user specify the file location. What's more, is that the little idiosyncrasies are built in to the function to read the file. But, what the function should expect is that things should have certain names etc.

The overarching issue here is that every step has it's preferred format, and they're all different. My stuff included. The thing that's closest to not requiring "additional formatting" is the `trawlData` functions. I'm going to check what those need. If I'm insanely lucky, I can just use those functions to do most of this.

I think a lot of the problem was that I initially thought "update" meant "add on the new stuff". So I needed to look for new data in once place, old data in another, and make them match up. But what we really want is "just redownload everything and start anew". However, the old method is somewhat justified, because we _need_ to match the old formatting, otherwise the server won't be able to feed the data sets into the OA data base. Personally, I still don't understand what happens on the server side of things. But there's a lot of switching back and forth between formats, which makes the whole damn thing pretty delicate. Point being: if the new data format doesn't line up with the old, everything falls apart, so it's still worth comparing the two and making sure they line up.

@mpinsky Yeah, we should talk. I basically have this year's data (except wcann and seus) in hand.

I also think that my previous approach was a bit more complicated than it had to be. I think I recycled the aspects of this code that I liked and were good in the trawlData code, but trawlData learned some lessons, I think.
