### ISSUE TITLE
GMEX station not reading into R

### ISSUE THREAD

**Issue by mpinsky** [mpinsky/OceanAdapt#42]
Heads up to @rBatt @danfarns 

There are quotation issues in the current Data_Updated/gmex/station.csv file, I think because it was read in by update.data.R and then written out without quotes. The same problem appears in data_download/Data_Vis_2015_09_04.zip (for gmex_station.csv). R spits an EOF error when it tries to read it in.

I believe I've fixed the problem by copying STAREC.csv rather than manipulating it in R. The file in Data_Updated/gmex_newstation.zip should be fine, and I will upload it to the website... once the website is ready to accept new files.

**Comment by ljmarxen** [comment]
The data on the website is fully up to date, so no need to reupload it.  
We were experiencing some issues with our data management script and Dan 
grabbed all the data from github and re-inserted it into the database 
manually to make sure everything was correct and up to date.  He had  
noticed there were some issues with the gmex files but didn't have time 
to investigate it.

On 09/08/2015 12:21 PM, mpinsky wrote:
>
> Heads up to @rBatt <https://github.com/rBatt> @danfarns 
> <https://github.com/danfarns>
>
> There are quotation issues in the current 
> Data_Updated/gmex/station.csv file, I think because it was read in by 
> update.data.R and then written out without quotes. The same problem 
> appears in data_download/Data_Vis_2015_09_04.zip (for 
> gmex_station.csv). R spits an EOF error when it tries to read it in.
>
> I believe I've fixed the problem by copying STAREC.csv rather than 
> manipulating it in R. The file in Data_Updated/gmex_newstation.zip 
> should be fine, and I will upload it to the website... once the 
> website is ready to accept new files.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mpinsky/OceanAdapt/issues/42>.
>

-- 
   Lucas Marxen
   Assistant Director of Research Technology
   Office of Research Analytics
   New Jersey Agricultural Experiment Station
   Rutgers, The State University of New Jersey
   Martin Hall, Room 113
   88 Lipman Drive
   New Brunswick, NJ 08901-8525
   Tel: 848-932-4543
   Email: marxen@aesop.rutgers.edu

**Comment by mpinsky** [comment]
@ljmarxen The problem also appears in the data when downloaded from the website (I just tested it), so I believe I need to upload a new version of the gmex/station.csv file when I can.

**Comment by rBatt** [comment]
Does the problem involve files that have been formatted by the update
script? That script hasn't been changed, and previously worked. My guess is
that the problem is with files that have no been run through that script.

Also, one of the gmex files doesn't read in properly unless you re-save it
first; there's a warning or message to this point in the update script.

**Comment by mpinsky** [comment]
The error is with a file that had been run through the update script. The
gmex/station.csv file was reading in incorrectly, so that much of the end
of the file was garbage.

I updated the update script to (hopefully) fix this and updated the
instructions as well. Rather than opening in Excel, we have to open in a
text editor and search&replace \" with "".

**Comment by danfarns** [comment]
@mpinsky 
The data in the database should still be fine, but outputting appears to be the primary problem.
I will take the following to confirm and fix where appropriate:
1. Double check the station file in /master/data_updates/Data_Updated/gmex_newstsation.zip versus the rows in the database and confirm that the data has been uploaded correctly. If not, refresh table with the rows stored in this zip file.
2. Force raw download to place quotes around fields as listed in the station CSV file. This should solve the issue here.

**Comment by mpinsky** [comment]
Hi Dan,

Perhaps, though, part of the problem is that R can't read in a file with
escaped double quotes (\"). I'd prefer to strip these out before they go in
the database.

Thanks for doing the update. I take it that the upload function isn't ready
yet on the website?

**Comment by mstuart1** [comment]
GMEX station is working
