### ISSUE TITLE
Settting effort in SEUS; typo?

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#44]
@JWMorley See here: https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L296-L297

In other places you referenced the `COLLECTIONNUMBER`, but here you did `EVENTNAME` for the same type of correction. Was that intentional?

Need to know for trawlData: https://github.com/rBatt/trawlData/issues/6

**Comment by ljmarxen** [comment]
I am out of the office until 11/9/15.

Your message was received and I will read it when I return. Any future
messages from you between now and when I return will be read at that
time also, but you will not receive any more automatic replies to that
effect.

**Comment by rBatt** [comment]
Also, for one of those event names I don't get any rows returned (i.e., the EVENTMENT doesn't exist in my data set??); for the other, I do get some rows.

Relates to rBatt/trawlData#6

**Comment by JWMorley** [comment]
This is intentional. seus has paired hauls, two COLLECTIONNUMBER per
EVENTNAME. In come cases only one of those paired tows needed fixing. In
others there was no EFFORT data for either COLLECTIONNUMBER, so I fixed
the EVENTNAME to get both hauls. I believe I calculated effort based on
start and end gps points.
Jim
